# version: 1.0
provider:
  name: openfaas
  # gateway: http://127.0.0.1:8080
functions:
  # api-proxy:
  #   lang: python3-flask
  #   handler: ./function/api-proxy
  #   # image: ghcr.io/EticaAI/osm-api-proxy:latest
  #   # image: EticaAI/osm-api-proxy:latest
  #   image: osm-api-proxy:latest

  api-proxy:
    lang: python3-http
    handler: ./function/api-proxy
    # image: api-proxy:latest
    image: ghcr.io/${OWNER:-fititnt}/api-proxy:${TAG:-latest}

  api-rdf:
    lang: python3-http
    handler: ./function/api-rdf
    image: ghcr.io/${OWNER:-fititnt}/api-rdf:${TAG:-latest}

  curl:
    lang: dockerfile
    handler: ./function/curl
    image: ghcr.io/${OWNER:-fititnt}/curl:${TAG:-latest}

  sentimentanalysis:
    lang: dockerfile
    handler: ./function/sentimentanalysis
    image: ghcr.io/${OWNER:-fititnt}/sentimentanalysis:${TAG:-latest}

# configuration:
#   templates:
#     - name: python3-http
#       source: https://github.com/openfaas/python-flask-template
